### ISSUE TITLE
Java 21+: Ensure `simple` client is closed

### ISSUE THREAD

**Issue by ybasket** [http4s/http4s-jdk-http-client#1011]
Java 21 adds methods to close a `HttpClient` and also makes it implement `AutoCloseable`: https://bugs.openjdk.org/browse/JDK-8267140

Ideally, http4s-jdk-http-client should leverage this and expose the `simple` client wrapped in a `Resource` to ensure the client is properly closed and cleaned up after use. Not sure how this can be achieved without requiring Java 21+ though, needs research.

**Comment by armanbilge** [comment]
We can just use reflection. I don't think it would be a hot-path.

The bigger issue is that our signatures currently return `F[_]` instead of `Resource`. This would have to be a breaking change 😕 

https://github.com/http4s/http4s-jdk-http-client/blob/21de6a2a0f5be5cda24042b424cf496b54e4a606/core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala#L247-L248

**Comment by rossabaker** [comment]
Does it need reflection, or can it just pattern match on AutoCloseable?

Why does it need to be a breaking change instead of another constructor?  The bigger problem I see is that the resource release would be a no-op on older JDK.

**Comment by armanbilge** [comment]
> Does it need reflection, or can it just pattern match on AutoCloseable?

👍 smart



> Why does it need to be a breaking change instead of another constructor?

You're right, it doesn't. See a prior discussion on a similar issue where we decided to break: https://github.com/http4s/http4s-jdk-http-client/pull/770#discussion_r1027315599.

**Comment by rossabaker** [comment]
That pattern match might require a nowarn when compiled on JDK21 for an unreachable fallback case.
